stages:
  - build
  - check

variables:
  BUILD_DIR: _build
  DRAKE_DEBUG_BACKTRACE: "1"
  DRAKE_EXPLAIN: "1"
  INSTALL_DIR: _install
  PROJECT: "elle"
  PYTHONUNBUFFERED: "1"
  GIT_SUBMODULE_STRATEGY: "recursive"

before_script:
  - NPROC=$(nproc)

build:
  stage: build
  image: registry.gitlab.gruntech.org/mefyl/elle/trusty-ci
  script:
    - farm/configure --arch x86_64 --os xenial --compiler gcc4 --project $PROJECT --source-dir "$CI_PROJECT_DIR" --build-dir "$BUILD_DIR" --install-dir "$INSTALL_DIR"
    - cd "$BUILD_DIR" && python3 drake -j $NPROC //build
  artifacts:
    name: "${CI_JOB_STAGE}_${CI_COMMIT_REF_NAME}"
    paths:
      - _build

check:
  stage: check
  image: registry.gitlab.gruntech.org/mefyl/elle/trusty-ci
  script:
    - cd "$BUILD_DIR" && python3 drake -j $NPROC //check
  dependencies:
    - build
  artifacts:
    name: "${CI_JOB_STAGE}_${CI_COMMIT_REF_NAME}"
    paths:
      - _build
