stages:
  - check

variables:
  PYTHONUNBUFFERED: "1"

check:x86_64-trusty-gcc4:
  stage: check
  image: registry.gitlab.gruntech.org/infinit/drake/trusty-ci
  script:
    - pip3 install -r requirements.txt coverage
    - src/bin/drake . --workdir _build --coverage=true
    - cd _build && coverage report
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
