stages:
  - build

variables:
  PYTHONUNBUFFERED: "1"

x86_64-trusty-gcc4:
  stage: build
  script:
    - git submodule update --init --recursive
    - git fetch origin --tags
    - mkdir -p ../elle-build ../elle-install
    - farm/configure --arch x86_64 --os trusty --compiler gcc4 --project Elle --source-dir . --build-dir ../elle-build --install-dir ../elle-install
    - cd ../elle-build && python3 drake -j 4 //build
    - cd ../elle-build && python3 drake -j 4 //check
    - cd ../elle-build && python3 drake -j 4 //install
  tags:
    - x86_64
    - trusty
    - gcc4

x86_64-jessie-gcc4:
  stage: build
  script:
    - git submodule update --init --recursive
    - git fetch origin --tags
    - mkdir -p ../elle-build ../elle-install
    - farm/configure --arch x86_64 --os jessie --compiler gcc4 --project Elle --source-dir . --build-dir ../elle-build --install-dir ../elle-install
    - cd ../elle-build && python3 drake -j 4 //build
    - cd ../elle-build && python3 drake -j 4 //check
    - cd ../elle-build && python3 drake -j 4 //install
  tags:
    - x86_64
    - jessie
    - gcc4

i386-jessie-gcc4:
  stage: build
  script:
    - git submodule update --init --recursive
    - git fetch origin --tags
    - mkdir -p ../elle-build ../elle-install
    - farm/configure --arch i386 --os jessie --compiler gcc4 --project Elle --source-dir . --build-dir ../elle-build --install-dir ../elle-install
    - cd ../elle-build && python3 drake -j 4 //build
    - cd ../elle-build && python3 drake -j 4 //check
    - cd ../elle-build && python3 drake -j 4 //install
  tags:
    - i386
    - jessie
    - gcc4

x86_64-windows-mingw4:
  stage: build
  script:
    - git submodule update --init --recursive
    - git fetch origin --tags
    - mkdir -p ../elle-build ../elle-install
    - farm/configure --arch x86_64 --os windows --compiler mingw4 --project Elle --source-dir . --build-dir ../elle-build --install-dir ../elle-install
    - cd ../elle-build && python3 drake -j 4 //build
    - cd ../elle-build && python3 drake -j 4 //check
    - cd ../elle-build && python3 drake -j 4 //install
  tags:
    - x86_64
    - windows
    - mingw4

i686-windows-mingw4:
  stage: build
  script:
    - git submodule update --init --recursive
    - git fetch origin --tags
    - mkdir -p ../elle-build ../elle-install
    - farm/configure --arch i686 --os windows --compiler mingw4 --project Elle --source-dir . --build-dir ../elle-build --install-dir ../elle-install
    - cd ../elle-build && python3 drake -j 4 //build
    - cd ../elle-build && python3 drake -j 4 //check
    - cd ../elle-build && python3 drake -j 4 //install
  tags:
    - i686
    - windows
    - mingw4

x86_64-osx-clang:
  stage: build
  script:
    - git submodule update --init --recursive
    - git fetch origin --tags
    - mkdir -p ../elle-build ../elle-install
    - farm/configure --arch x86_64 --os osx --compiler clang --project Elle --source-dir . --build-dir ../elle-build --install-dir ../elle-install
    - cd ../elle-build && python3 drake -j 4 //build
    - cd ../elle-build && python3 drake -j 4 //check
    - cd ../elle-build && python3 drake -j 4 //install
    - TARBALL=elle-x86_64-osx-clang3-$(GIT_DIR=../elle/.git git describe).tbz
    - gtar -cvjf /tmp/$TARBALL -C ../elle-install . --show-transformed-names --transform "s,^\\./,infinit-$(GIT_DIR=../elle/.git git describe)/,"
  tags:
    - x86_64
    - osx
    - clang
